### ISSUE TITLE
Woocommerce removed

### ISSUE THREAD

**Issue by rajatsingh828** [teligro/teligro#1]
Didn't receive any message from.telegram.of woocommerce , so thought i would check on and now woocommerce is no where to be found on your plugin

woocommerce plugin is active too

https://telegra.ph/file/6610887d450a44010ceba.png

**Comment by parsakafi** [comment]
Hello
What's your version of WooCommerce?

Deactivate Teligro and active again, and check if the WooCommerce tab in Teligro settings displayed or not.

https://ps.w.org/teligro/assets/screenshot-3.png?rev=2406171

**Comment by rajatsingh828** [comment]
Woocommerce v4.7.0

Was using wp telegram pro as backup now deactivating and activating worked for teligro.

now i can see woocommerce tab but settings are lost.

**Comment by parsakafi** [comment]
Yes, there is a problem
Will be resolved in later versions.

**Comment by rajatsingh828** [comment]
Thanks dude , love your plugin and for fast reply to queries
